services:
  csengo-v2-postgres:
    container_name: csengo-v2-postgres
    image: postgres:16.6
    restart: always
    ports:
      - '5582:5432'
    environment:
      POSTGRES_USER: csengo
      POSTGRES_PASSWORD: csengo
      POSTGRES_DB: csengo
    volumes:
      - csengo-v2_db:/var/lib/postgresql/data
      - csengo-v2_db_init:/docker-entrypoint-initdb.d
    networks:
      - csengo-v2

  csengo-ts-server-v2:
    container_name: csengo-ts-server-v2
    image: ghcr.io/pollak-projects/csengo-ts/server-app:latest
    restart: always
    volumes:
      - csengo-v2_sounds:/data
    ports:
      - "7666:3300"
    depends_on:
      - csengo-v2-postgres
    networks:
      - csengo-v2
    environment:
      PORT: 3300
      DATABASE_URL: "postgresql://csengo:csengo@csengo-v2-postgres:5432/csengo?schema=public"
      UPLOAD_PATH: "./data/audio"
      UPLOAD_TEMP_PATH: './data/temp'
      TOKEN_SECRET: "token-secret"
      JWT_SECRET: "jwt-secret"
      CORS_ORIGIN: ".*[a-z0-9]*.4o1x5.dev"
      CORS_DOMAIN: "4o1x5.dev"
      DEV: true

  csengo-ts-client-v2:
    container_name: csengo-ts-client-v2
    image: ghcr.io/pollak-projects/csengo-ts/client-app:latest
    ports:
      - "7665:80"
    networks:
      - csengo-v2

  csengo-v2-pgadmin:
    container_name: csengo-v2-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "7667:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@4o1x5.dev
      PGADMIN_DEFAULT_USERNAME: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    volumes:
      - csengo-v2_pgadmin:/var/lib/pgadmin
    networks:
      - csengo-v2

networks:
  csengo-v2:

volumes:
  csengo-v2_db:
  csengo-v2_db_init:
  csengo-v2_sounds:
  csengo-v2_pgadmin:
